edgexfoundry/app-rfid-llrp-inventory

.dockerignore
Dockerfile
Jenkinsfile
Makefile
go.mod
internal/llrp/device_service.go
internal/llrp/reader_group.go
main.go
res/configuration.toml
snap/snapcraft.yaml

https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r583947835
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r583950535
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r583951169
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r583955046
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r583956205
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r583957040
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r583957266
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r583957608 …

Fixes first set of PR review comments

---

internal/llrp/llrp_structs_test.go

Correct merged in reflect pkg, when it is not needed.
Signed-off-by: Samantha Coyle <samantha.coyle@intel.com>
Issue Number:

fix(test): correct merged import

---

internal/inventory/config.go
internal/inventory/event.go
internal/inventory/location.go
internal/inventory/reportinfo.go
internal/inventory/tag.go
internal/inventory/tagprocessor.go
internal/llrp/behavior.go
internal/llrp/llrp_structs_test.go
internal/llrp/reader_group_test.go
main.go

And add documentation for confusing sections of code.
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r588705454
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r588708218
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r588709193
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r588714877
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r588715408
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r588702969
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r588701873 …

Add godoc for exported members

---

internal/llrp/device_service_test.go

Added Unit test case file for internal/llrp/device_service.go, addressing following code review comment -
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18/files/4ed75eca7294d7fdc6881789667a4ba32fc4d021#r595522154

Unit Test Case Addition, Addressing Code Review Comments

---

README.md
internal/inventory/tagprocessor_test.go
internal/inventory/testdataset_utility_test.go
internal/llrp/behavior.go
internal/llrp/behavior_test.go
internal/llrp/device_service.go
internal/llrp/llrp_structs_test.go
internal/llrp/reader_group_test.go
main.go

https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r592742082
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r592744452
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r592749341
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r592752055
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r592757921
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r592759129
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r595545527
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r595547239 …

Misc pr fixes

---

Dockerfile.build
Makefile
go.mod

- Add go mod tidy to align to other Makefile's
- Update to Go 1.16 to align to other EdgeX repos
- Add Dockerfile.build fo CI pipeline
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>
Issue Number:

ci: add go mod tidy for ci pipeline

---

.github/PULL_REQUEST_TEMPLATE.md
Attribution.txt
Dockerfile
Jenkinsfile
Makefile
README.md
go.mod
internal/inventory/app/app.go
internal/inventory/app/controller.go
internal/inventory/app/mock_config_client_test.go
internal/inventory/app/routes.go
internal/inventory/tagprocessor.go
internal/inventory/testdataset_utility_test.go
internal/llrp/device_service.go
main.go
res/configuration.toml
snap/snapcraft.yaml

Signed-off-by: lenny <leonard.goodell@intel.com>
old names are still in import statements , mod file, etc
Issue Number: n/a
New names now used in import statements , mod file, etc

build: Adjust names for repo moved out of holding and renamed.

---

internal/llrp/util.go
internal/llrp/util_test.go

N/A
Added a few additional unit test cases, removed a lot of superfluous code, renamed fields and tests.
No
I reordered some of the unit test functions, so GitHub is having a hard time matching up the diffs.

refactor(test): Cleanup llrp util unit tests

---

GOVERNANCE.md
OWNERS.md
res/configuration.toml

Mix of single quotes and double quotes in TOML Files
Issue Number: n/a
Replaced single quotes with double quotes in TOML Files
Added governance.md and owner.md files for LF Edge
no

refactor: Clean up TOML quotes, commit go.sum and add LF MD files

---

.gitignore
internal/inventory/app/app.go
internal/llrp/device_service.go
internal/llrp/device_service_test.go
internal/llrp/reader_group.go
internal/llrp/reader_group_test.go

Closes #34
Signed-off-by: Anthony Casagrande <anthony.j.casagrande@intel.com>
Issue Number: #34
Retry when an HTTP GET call is unsuccessful up to 5 tries.
No

fix: Retry failed HTTP GET calls

---

.github/workflows/snap.yaml
Jenkinsfile

The workflow added here will activate only after it has been merged into the main. In the meantime, https://github.com/MonicaisHer/app-rfid-llrp-inventory/pull/1 that is against the fork can be taken as a reference.
Signed-off-by: Mengyi Wang <mengyi.wang@canonical.com>

test(snap): add snap CI workflow

---

README.md

Signed-off-by: Marc-Philippe Fuller <marc-philippe.fuller@intel.com>
N/A

fix: changed all 'rfid-llrp-inventory' to 'app-rfid-llrp-inventory'

---

CHANGELOG.md

Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

docs: Update change log for Kamakura

---

internal/inventory/app/app.go

1.  use local image of app-rfid-llrp
2.  check consul  key/value for app-rfid-llrp app custom config
3. change the config in res/configuration.toml and make new image local image
4. reload edgex stack and  check app custom config for changed configs

Fix custom config

---

Dockerfile
Makefile
README.md
res/configuration.toml

Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

build: Add option to build Service with NATS Capability

---

internal/llrp/behavior.go
internal/llrp/llrp_structs.go

refactor: Go 1.20 gofmt

---

Dockerfile
Makefile
go.mod
internal/inventory/app/controller.go
internal/inventory/app/routes.go
snap/local/helper-go/go.mod
snap/snapcraft.yaml

run non-secure edgex stack  
build and run service from this branch 
verify service bootstraps w/o error

build: Update to Go 1.20, Alpine 3.17 and linter v1.51.2

---

.github/dependabot.yml

ci: Change dependabot gomod schedule to daily

---

.github/dependabot.yml

build: [App LLRP] Ignore all go-mod deps, except go-mod-bootstrap

---

README.md

docs: [App LLRP] Add main branch Warning

---

CHANGELOG.md
Jenkinsfile
go.mod
go.sum

Run EdgeX Secure Stack
Run make docker
From compose builder run `make run ds-virtual app-dev`
Verify common endpoints, except ping, require JWT token
Verify ping endpoint doesn't require JWT token

build: Update for patch 3.0.1 release

---

Attribution.txt
go.mod
go.sum
internal/inventory/app/app.go
internal/inventory/app/controller.go
internal/inventory/app/routes.go
internal/inventory/config.go
internal/llrp/behavior.go
internal/llrp/device_service.go
internal/llrp/reader_group.go

refactor: Replace github.com/pkg/errors with errors

---

Dockerfile
Makefile
go.mod
internal/llrp/device_service_test.go

make test
make build
make docker
Verify all are successful

build: Upgrade to go-1.21, Linter1.54.2 and Alpine 3.18

---

res/configuration.yaml

refactor: Remove obsolete comments from config file

---

openapi/v3/app-rfid-llrp-inventory.yaml

docs: [App LLRP] Add swagger file

---

CHANGELOG.md

docs: Update chengelog for release 3.1

---

go.mod
go.sum
internal/inventory/app/routes.go

1. Start up edgex with `no-secty ds-llrp`
2. start up llrp simulator
3. use curl commands listed [here](https://docs.edgexfoundry.org/3.1/microservices/application/services/AppLLRPInventory/ApiReference/) to test endpoints 
4. verify end points work as expected

fix: Adjust handlers to use Echo signature
